version: '3.6'
services:
  react:
    image: node
    ports:
      - '3003:3003'
    working_dir: /home/node/app
    volumes:
      - './app:/home/node/app'
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"